Added stacker tests.
philipdesmedt/arkadiko-dao pull request #103
Opened 2021-05-25 16:06 UTC by nieldeckx

Additional tests

2021-05-27 10:39 UTC, nieldeckx commented
Fixed bug and added test. (not through freddie as discussed as this creates a circular dependency with stacker)

2021-05-28 08:53 UTC, philipdesmedt requested changes

2021-05-28 08:53 UTC, philipdesmedt commented on clarity/contracts/arkadiko-stacker-v1-1.clar
> +        (try! (contract-call? .arkadiko-vault-data-v1-1 update-vault vault-id (merge vault {
REQ: don't we need to keep two calls (i.e. the one I had on line 232)? Since now the vault is only updated with the new collateral amount if the vault owner has revoked stacking, which is not always the case? They always get the new collateral, if they revoked stacking or not.

2021-05-31 11:45 UTC, philipdesmedt commented on clarity/contracts/arkadiko-stacker-v1-1.clar
> +        (try! (contract-call? .arkadiko-vault-data-v1-1 update-vault vault-id (merge vault {
nvm - this is correct

2021-05-31 11:45 UTC, merged