Nd/staking registry
philipdesmedt/arkadiko-dao pull request #72
Opened 2021-04-27 19:46 UTC by nieldeckx

- Stake-registry to keep track of active pools and rewards for each pool
- Emergency withdraw method on stake-pool-diko + test

2021-04-28 13:39 UTC, philipdesmedt requested changes

2021-04-28 13:39 UTC, philipdesmedt commented on clarity/contracts/stake-pool-diko.clar
> +      (amount (unwrap! (get-balance-of tx-sender) ERR-NOT-AUTHORIZED))
General comment here since I have a few of these as well in the code that I wrote, but

we probably need a generic error (like you have a status 500 on the web). Not authorized is not really applicable here. Everyone is authorized to see any principal's balance, but for whatever reason that goes wrong, we could throw an error 500-like error code.

An alternative would be to use `unwrap-panic` instead of `unwrap!`, but this could give issues on the front-end, since it "crashes" the whole smart contract call and doesn't allow for clean error catching in the front-end.

2021-04-28 13:39 UTC, philipdesmedt commented on clarity/contracts/stake-registry.clar
> +  (map-set pools-data-map
Q: how do we change the `rewards-per-block` value? I don't see a setter?

2021-04-29 07:33 UTC, nieldeckx commented on clarity/contracts/stake-registry.clar
> +  (map-set pools-data-map
To change the rewards, you need to publish a new stake-registry contract and set this contract in the DAO.

This way we don't need a specific proposal type when changing rewards.

2021-04-29 07:35 UTC, nieldeckx commented on clarity/contracts/stake-pool-diko.clar
> +      (amount (unwrap! (get-balance-of tx-sender) ERR-NOT-AUTHORIZED))
Would be better to catch the actual error but if that does not work with the FE, we need an alternative. Will change to 500.

2021-04-29 09:12 UTC, philipdesmedt commented on clarity/contracts/stake-registry.clar
> +  (map-set pools-data-map
@nieldeckx but our rewards change every two weeks with our supply schedule, so every two weeks we need to publish a new contract?

2021-04-29 10:18 UTC, philipdesmedt commented on clarity/contracts/stake-pool-diko.clar
> +      (amount (unwrap! (get-balance-of tx-sender) ERR-NOT-AUTHORIZED))
So the actual error works. We can make a real error for it (e.g. not a generic 500), but what I'm saying is that `unwrap-panic` does not work since it throws some uncaught exception.

2021-04-29 10:41 UTC, nieldeckx commented on clarity/contracts/stake-registry.clar
> +  (map-set pools-data-map
With this setup, yes. :)

I'm working on a new contract (diko-guardian) to implement the supply schedule. The stake-registry will divide the total staking rewards defined by diko-guardian over the different pools. The "rewards-per-block" will change to "rewards-percentage".

2021-04-29 10:59 UTC, philipdesmedt commented on clarity/contracts/stake-registry.clar
> +  (map-set pools-data-map
@nieldeckx all right, great. I'll review & merge this then.

2021-04-29 12:23 UTC, merged