Nd/return votes
philipdesmedt/arkadiko-dao pull request #73
Opened 2021-04-28 11:10 UTC by nieldeckx

- Can now vote with DIKO and stDIKO
- Once proposal ends, tokens can be claimed

2021-04-28 13:15 UTC, philipdesmedt requested changes
Looks good.. just one question

2021-04-28 13:15 UTC, philipdesmedt commented on clarity/contracts/governance.clar
> +    (is-stdiko (is-eq (contract-of token) .stake-pool-diko))
Q: hardcoding this as `stake-pool-diko` means that we can never replace the stake pool, right? 

I guess this is fine, since we define the stDIKO there, but I just thought of this 😬

2021-04-29 07:30 UTC, nieldeckx commented on clarity/contracts/governance.clar
> +    (is-stdiko (is-eq (contract-of token) .stake-pool-diko))
Correct. Rewards can be changed through the stake-registry though.

2021-04-29 09:09 UTC, philipdesmedt commented
@nieldeckx thx for reply, will test the branch & merge if good

2021-04-29 10:20 UTC, merged