Nd/diko guardian
philipdesmedt/arkadiko-dao pull request #78
Opened 2021-05-02 08:46 UTC by nieldeckx

DIKO guardian looks after the DIKO supply schedule:
- Calculate staking rewards per block (for all pools)
- Allow founders to claim tokens

2021-05-02 13:19 UTC, philipdesmedt requested changes
Nice work! Wasn't easy.

Some questions + will try if the staking front-end still works

2021-05-02 13:19 UTC, philipdesmedt commented on clarity/contracts/diko-guardian.clar
> +(define-data-var staking-rewards-first-year uint u25000000000000) ;; 25m with 6 decimals
Q: shouldn't this be a constant? Or do you think this will still be changed once we deploy this?

2021-05-02 13:19 UTC, philipdesmedt commented on clarity/contracts/diko-guardian.clar
> +    ;; Extra multiplier of 98.5% - makes sure we remain below our targets
Q: how is the 98.5% calculated? Is this just a random number you arrived at to cancel out rounding errors and things like that?

2021-05-02 13:19 UTC, philipdesmedt commented on clarity/contracts/diko-guardian.clar
> +      (if (> month-number u59)
Q: This means 5 year vesting? 

Usually the 1 year cliff is included in the 4 years, meaning you vest over 4 years but if one of the founders quits within the first year, it means they didn't get "past the cliff", meaning 0 tokens are vested. From year 2, month 1, the tokens accumulate monthly.

Either way I don't mind if it's 48 months or 60 months - but just so we are all clear on this

2021-05-02 13:50 UTC, nieldeckx commented on clarity/contracts/diko-guardian.clar
> +(define-data-var staking-rewards-first-year uint u25000000000000) ;; 25m with 6 decimals
Yes, will change to a constant. If we want to change it, we deploy a new contract :)

2021-05-02 13:55 UTC, nieldeckx commented on clarity/contracts/diko-guardian.clar
> +    ;; Extra multiplier of 98.5% - makes sure we remain below our targets
Yes. Without it, we would be just above 25m DIKO after 1 year. 
I think we could increase the precision and lower this multiplier, but it won't change the end result much.

2021-05-02 14:01 UTC, nieldeckx commented on clarity/contracts/diko-guardian.clar
> +      (if (> month-number u59)
I misunderstood the docs, but fully agree to implement the most common way. Will update.

2021-05-02 15:57 UTC, philipdesmedt approved these changes
Staking still works. Added the smart contract deployment to mocknet.

Will leave this PR open for a bit longer to look at the code again.

2021-05-03 15:23 UTC, philipdesmedt commented
@nieldeckx 
I want to consider exploring lowering the 1 year cliff to 6 months to protect people attacking the protocol through staking (i.e. acquiring a lot of DIKO in the early days through minting & stacking & minting & ...). Us vesting tokens after 6 months & using some foundation tokens can more effectively protect us from this.

Will discuss on Wednesday

2021-05-03 16:32 UTC, nieldeckx commented
@philipdesmedt Besides the attack you described, governance now has the ability to remove all founders/foundation rewards by pushing new contracts. This might put the project at risk long term.

2021-05-06 15:07 UTC, merged