[1] Refactor auction to remove external call
philipdesmedt/arkadiko-dao pull request #93
Opened 2021-05-11 16:43 UTC by nieldeckx

Removed the need for "is-accepted" on an auction. When a bid is made and it can be accepted, it is immediately accepted. Once the auction ends, all current bids are accepted. This removes the external "unlock-winning-lot" call.

Also removed "is-open" from the auction. We can calculate if the auction is open on the spot. This decreases the dependency on the external "clause-auction" call.

Improved the errors to reflect the new logic.

2021-05-12 05:46 UTC, philipdesmedt reviewed
Will have to change the front-end to adapt to this change. Gonna do it in this PR

2021-05-12 05:46 UTC, philipdesmedt commented on clarity/contracts/arkadiko-auction-engine-v1-1.clar
> +      (try! (contract-call? vault-manager redeem-auction-collateral ft reserve (get collateral-amount last-bid) tx-sender))
Q: have we tested passing a wrong token/reserve here?

2021-05-12 21:10 UTC, philipdesmedt commented
@nieldeckx I started on this in the front-end, but it's not straightforward :)

I will continue when I get back, Sunday/Monday. Feel free to continue testing branching off of this branch.

2021-05-13 13:59 UTC, nieldeckx commented on clarity/contracts/arkadiko-auction-engine-v1-1.clar
> +      (try! (contract-call? vault-manager redeem-auction-collateral ft reserve (get collateral-amount last-bid) tx-sender))
Have added tests, but have added one TODO as not sure what happens. Can you have a look and let me know please?

2021-05-16 18:21 UTC, philipdesmedt requested changes

2021-05-16 18:21 UTC, philipdesmedt commented on clarity/contracts/arkadiko-auction-engine-v1-1.clar
> +    (try! (contract-call? .arkadiko-vault-data-v1-1 add-stacker-payout (get vault-id auction) collateral-amount tx-sender))
REQ: I think this is a problem.

We can only register the stacker payout once we know the bid is final (i.e. the person has won the bid). Right now, if someone overbids, then we add a stacker payout twice (one for the now losing bid and one for the current winning bid). This can go on N times for N bids.

2021-05-16 19:17 UTC, philipdesmedt commented
@nieldeckx I'm not sure how to make this work to be honest

1. We have the stacker issue that I mentioned
2. I don't know how to show the winning lots in the UI without re-introducing the map.
3. It now is only possible for liquidators to get access to the collateral once the whole auction is closed and not per lot they won. This might not be a problem in practice as auctions only run one day.

I'm not sure this is a net win vs the other approach we had after all 😬  I'll try to re-introduce the map first and see if I can fix things that way

2021-05-17 06:42 UTC, philipdesmedt commented
@nieldeckx think this is done 😅

2021-05-17 10:40 UTC, philipdesmedt commented
@nieldeckx I merged everything in this branch... I really hope I didn't screw up some merge conflicts, there were a ton of changes - likely I missed a test here or there :/

2021-05-17 10:40 UTC, merged